# Generated by scripts/render-packaging.sh for v0.7.17. Do not edit by hand.
class SuperHerdr < Formula
  desc "Multi-host federation client for Herdr sessions"
  homepage "https://github.com/mikro-design/super-herdr"
  version "0.7.17"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.17/super-herdr-v0.7.17-aarch64-apple-darwin.tar.gz"
      sha256 "1ad931293b07450945c3edb8833e0b9f3e19339a6a995d0198404a80498c83c6"
    end
    on_intel do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.17/super-herdr-v0.7.17-x86_64-apple-darwin.tar.gz"
      sha256 "8c72cc960835a9f1e77e4210490bd5091cd325225e17201ad8571ad263c1c534"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.17/super-herdr-v0.7.17-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "262d927fd31cd5d0e6b743e0ed489d963fbb63c143d7731badfc6b3b0fd77ede"
    end
    on_intel do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.17/super-herdr-v0.7.17-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b91a68257e1d14836741ebcbba25943267e8c6e265fae7d5b7a45bfd44b35e32"
    end
  end

  def install
    bin.install "super-herdr"
    doc.install "README.md", "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    assert_match "super-herdr #{version}", shell_output("#{bin}/super-herdr --version")
  end
end
