# Generated by scripts/render-packaging.sh for v0.7.0. Do not edit by hand.
class SuperHerdr < Formula
  desc "Multi-host federation client for Herdr sessions"
  homepage "https://github.com/mikro-design/super-herdr"
  version "0.7.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.0/super-herdr-v0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "a18fa50de8edf6114aa7a58e06f79f3df1c494623ca1bdbab4acbc9679613c1c"
    end
    on_intel do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.0/super-herdr-v0.7.0-x86_64-apple-darwin.tar.gz"
      sha256 "cbde17c60723c6216129d4df0d88bef1e3254249624b38b2df8c39856b7dd053"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.0/super-herdr-v0.7.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "5cd2df8fa787c9a152bea4feebc7d71b9306fc5e13b25b7ad792f89f295acd21"
    end
    on_intel do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.7.0/super-herdr-v0.7.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8da1a90e32d65e16eb274d046c81e6f605c7952512d19eb77c53b5497cfcf297"
    end
  end

  def install
    bin.install "super-herdr"
    doc.install "README.md", "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    assert_match "super-herdr #{version}", shell_output("#{bin}/super-herdr --version")
  end
end
