# Generated by scripts/render-packaging.sh for v0.4.1. Do not edit by hand.
class SuperHerdr < Formula
  desc "Multi-host federation client for Herdr sessions"
  homepage "https://github.com/mikro-design/super-herdr"
  version "0.4.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.4.1/super-herdr-v0.4.1-aarch64-apple-darwin.tar.gz"
      sha256 "18b373a2b06233b8ed1254f4d4c8554a9eee76475789d0623a49dd38e0ef7e1f"
    end
    on_intel do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.4.1/super-herdr-v0.4.1-x86_64-apple-darwin.tar.gz"
      sha256 "75ce522a49d5b6541b5ff63af5dadcc6df33f14237ca20423b88ffe707d43625"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.4.1/super-herdr-v0.4.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cc469a5a2cdcfb37e404b4cb81dfa71bcf9b6b760f862354c14fecb5e84ce7b4"
    end
    on_intel do
      url "https://github.com/mikro-design/super-herdr/releases/download/v0.4.1/super-herdr-v0.4.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "843898d8dd52321cf4d7fe3bb223e09c24dd65161da0fcc9d4dfeb39b7a838e1"
    end
  end

  def install
    bin.install "super-herdr"
    doc.install "README.md", "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    assert_match "super-herdr #{version}", shell_output("#{bin}/super-herdr --version")
  end
end
